// Ultimate Sports UI string table.
// Loaded by the shell boot loader; app.js uses window.UltimateStrings[lang][key].
(function (root) {
  'use strict'

  const strings = {
    EN: {
      home: 'Home',
      bracket: 'Bracket',
      watch: 'Watch',
      games: 'Games',
      wallet: 'Wallet',
      settings: 'Settings',
      profile: 'Profile',
      pools: 'Pools',
      leaderboard: 'Leaderboard',
      friends: 'Friends',
      rooms: 'Rooms',
      chat: 'Chat',
      invite: 'Invite',
      join: 'Join',
      leave: 'Leave',
      cancel: 'Cancel',
      save: 'Save',
      submit: 'Submit',
      practice: 'Practice free',
      stake: 'Stake',
      createRoom: 'Create room',
      joinRoom: 'Join room',
      copyLink: 'Copy invite link',
      roomCode: 'Room code',
      waitingOpponent: 'Waiting for opponent…',
      connecting: 'Connecting…',
      matchOver: 'Match over',
      youWin: 'You win!',
      youLose: 'You lost',
      draw: 'Dead level!',
      backToLobby: 'Back to lobby',
      emptyPools: 'No pools open yet.',
      emptyLeaderboard: 'No scores yet — make the first pick.',
      emptyFriends: 'No friends online.',
      emptyRooms: 'No rooms yet.',
      emptyChat: 'No messages yet. Say hello!',
      emptyNotifications: 'Nothing new.',
      errorGeneric: 'Something went wrong.',
      loading: 'Loading…',
      live: 'Live',
      soon: 'Soon',
      final: 'Final',
      chooseWinner: 'Choose a winner',
      confidence: 'Confidence',
      survivor: 'Survivor',
      upsetBounty: 'Upset Bounty',
      sideQuest: 'Side Quest',
      totalStake: 'Total stake',
      prize: 'Prize',
      demo: 'Demo',
      realMoney: 'Real money'
    },
    PT: {
      home: 'Início',
      bracket: 'Chave',
      watch: 'Assistir',
      games: 'Jogos',
      wallet: 'Carteira',
      settings: 'Configurações',
      profile: 'Perfil',
      pools: 'Bolões',
      leaderboard: 'Classificação',
      friends: 'Amigos',
      rooms: 'Salas',
      chat: 'Chat',
      invite: 'Convidar',
      join: 'Entrar',
      leave: 'Sair',
      cancel: 'Cancelar',
      save: 'Salvar',
      submit: 'Enviar',
      practice: 'Praticar de graça',
      stake: 'Apostar',
      createRoom: 'Criar sala',
      joinRoom: 'Entrar na sala',
      copyLink: 'Copiar link',
      roomCode: 'Código da sala',
      waitingOpponent: 'Aguardando oponente…',
      connecting: 'Conectando…',
      matchOver: 'Partida encerrada',
      youWin: 'Você venceu!',
      youLose: 'Você perdeu',
      draw: 'Empate!',
      backToLobby: 'Voltar ao lobby',
      emptyPools: 'Nenhum bolão aberto ainda.',
      emptyLeaderboard: 'Nenhuma pontuação ainda — faça o primeiro palpite.',
      emptyFriends: 'Nenhum amigo online.',
      emptyRooms: 'Nenhuma sala ainda.',
      emptyChat: 'Nenhuma mensagem ainda. Diga oi!',
      emptyNotifications: 'Nada de novo.',
      errorGeneric: 'Algo deu errado.',
      loading: 'Carregando…',
      live: 'Ao vivo',
      soon: 'Em breve',
      final: 'Final',
      chooseWinner: 'Escolha um vencedor',
      confidence: 'Confiança',
      survivor: 'Sobrevivente',
      upsetBounty: 'Recompensa de Zebras',
      sideQuest: 'Missão Extra',
      totalStake: 'Aposta total',
      prize: 'Prêmio',
      demo: 'Demo',
      realMoney: 'Dinheiro real'
    },
    ES: {
      home: 'Inicio',
      bracket: 'Cuadro',
      watch: 'Ver',
      games: 'Juegos',
      wallet: 'Billetera',
      settings: 'Ajustes',
      profile: 'Perfil',
      pools: 'Quinielas',
      leaderboard: 'Tabla',
      friends: 'Amigos',
      rooms: 'Salas',
      chat: 'Chat',
      invite: 'Invitar',
      join: 'Unirse',
      leave: 'Salir',
      cancel: 'Cancelar',
      save: 'Guardar',
      submit: 'Enviar',
      practice: 'Practicar gratis',
      stake: 'Apostar',
      createRoom: 'Crear sala',
      joinRoom: 'Unirse a sala',
      copyLink: 'Copiar enlace',
      roomCode: 'Código de sala',
      waitingOpponent: 'Esperando oponente…',
      connecting: 'Conectando…',
      matchOver: 'Partido terminado',
      youWin: '¡Ganaste!',
      youLose: 'Perdiste',
      draw: '¡Empate!',
      backToLobby: 'Volver al lobby',
      emptyPools: 'Aún no hay quinielas abiertas.',
      emptyLeaderboard: 'Aún no hay puntajes — haz el primer pronóstico.',
      emptyFriends: 'Ningún amigo en línea.',
      emptyRooms: 'Aún no hay salas.',
      emptyChat: 'Aún no hay mensajes. ¡Saluda!',
      emptyNotifications: 'Nada nuevo.',
      errorGeneric: 'Algo salió mal.',
      loading: 'Cargando…',
      live: 'En vivo',
      soon: 'Pronto',
      final: 'Final',
      chooseWinner: 'Elige un ganador',
      confidence: 'Confianza',
      survivor: 'Superviviente',
      upsetBounty: 'Recompensa de Sorpresas',
      sideQuest: 'Misión Extra',
      totalStake: 'Apuesta total',
      prize: 'Premio',
      demo: 'Demo',
      realMoney: 'Dinero real'
    },
    FR: {
      home: 'Accueil',
      bracket: 'Tableau',
      watch: 'Regarder',
      games: 'Jeux',
      wallet: 'Portefeuille',
      settings: 'Paramètres',
      profile: 'Profil',
      pools: 'Pools',
      leaderboard: 'Classement',
      friends: 'Amis',
      rooms: 'Salles',
      chat: 'Chat',
      invite: 'Inviter',
      join: 'Rejoindre',
      leave: 'Quitter',
      cancel: 'Annuler',
      save: 'Enregistrer',
      submit: 'Valider',
      practice: 'S\'entraîner gratuitement',
      stake: 'Miser',
      createRoom: 'Créer une salle',
      joinRoom: 'Rejoindre une salle',
      copyLink: 'Copier le lien',
      roomCode: 'Code de la salle',
      waitingOpponent: 'En attente de l\'adversaire…',
      connecting: 'Connexion…',
      matchOver: 'Match terminé',
      youWin: 'Vous avez gagné !',
      youLose: 'Vous avez perdu',
      draw: 'Match nul !',
      backToLobby: 'Retour au lobby',
      emptyPools: 'Aucun pool ouvert pour l\'instant.',
      emptyLeaderboard: 'Aucun score pour l\'instant — soyez le premier.',
      emptyFriends: 'Aucun ami en ligne.',
      emptyRooms: 'Aucune salle pour l\'instant.',
      emptyChat: 'Aucun message pour l\'instant. Dites bonjour !',
      emptyNotifications: 'Rien de neuf.',
      errorGeneric: 'Une erreur est survenue.',
      loading: 'Chargement…',
      live: 'En direct',
      soon: 'Bientôt',
      final: 'Finale',
      chooseWinner: 'Choisissez un vainqueur',
      confidence: 'Confiance',
      survivor: 'Survivant',
      upsetBounty: 'Prime aux surprises',
      sideQuest: 'Quête secondaire',
      totalStake: 'Mise totale',
      prize: 'Prix',
      demo: 'Démo',
      realMoney: 'Argent réel'
    }
  }

  function t (key, lang) {
    const l = (lang || (root.state && root.state.language) || 'EN').toUpperCase()
    const table = strings[l] || strings.EN
    return table[key] !== undefined ? table[key] : strings.EN[key] !== undefined ? strings.EN[key] : key
  }

  root.ULTIMATE_UI_STRINGS = strings
  root.ULTIMATE_UI_T = t

  if (typeof module !== 'undefined' && module.exports) module.exports = { strings, t }
})(typeof globalThis !== 'undefined' ? globalThis : window)
