// Ultimate Sports fit registry. Each fit file calls registerFit(id, config).
(function (root) {
  'use strict'
  root.ULTIMATE_FIT_REGISTRY = root.ULTIMATE_FIT_REGISTRY || {}
  root.registerFit = function (id, config) {
    root.ULTIMATE_FIT_REGISTRY[id] = config
  }

  // Standard asset-pack layout generated by scripts/generate-fit-assets.js.
  // Paths are relative to shell/index.html (one level under the platform root).
  root.defaultFitAssets = function (fitId) {
    const base = '../generated-assets/' + fitId
    return {
      heroBackdrop: base + '/hero-backdrop/hero.jpg',
      serverCardCover: base + '/server-card-cover/cover.jpg',
      lobbyIcon: base + '/lobby-icon/icon.svg',
      poolCardAccent: base + '/pool-card-accent/accent.svg',
      miniGameIconSet: base + '/mini-game-icon-set/icons.svg',
      bracketBoardSkin: base + '/bracket-board-skin/board.jpg',
      watchRoomStage: base + '/watch-room-stage/stage.jpg',
      resultShareCard: base + '/result-share-card/share.jpg',
      emptyStateIllustration: base + '/empty-state-illustration/empty.jpg'
    }
  }
})(window)
