// Generic themed fits for all non-MMA, non-World-Cup event shapes.
// Generated by scripts/generate-generic-fit-data.js
(function (root) {
  'use strict'

  function makeTheme (primary, secondary, accent, ink, soft, surface) {
    return {
      '--ink': ink || '#4a3b57',
      '--muted': '#a897b3',
      '--soft': soft || '#fff0f8',
      '--surface': surface || '#ffffff',
      '--surface-2': '#fdf5fb',
      '--surface-3': '#f6eeff',
      '--line': '#ffd9ee',
      '--line-strong': '#f3c8e2',
      '--green': primary,
      '--green-deep': accent,
      '--red': secondary,
      '--pink': secondary,
      '--pink-deep': accent,
      '--blue': '#7cc4ff',
      '--blue-deep': '#3a90dd',
      '--grape': '#b79bff',
      '--gold': '#f0b93f',
      '--lemon': '#ffd76b'
    }
  }

  // Euros / Copa America
  const euros_copa_america_data = (function () {
    const teams = [{"id":"fr","name":"France","flag":"🇫🇷","colors":["#1d3d8f","#ffffff","#d84a3a"]},{"id":"de","name":"Germany","flag":"🇩🇪","colors":["#000000","#dd0000","#ffce00"]},{"id":"es","name":"Spain","flag":"🇪🇸","colors":["#c60b1e","#ffc400","#75131a"]},{"id":"eng","name":"England","flag":"🏴","colors":["#ffffff","#d41f35","#1c3764"]},{"id":"pt","name":"Portugal","flag":"🇵🇹","colors":["#d71920","#006b3f","#f6c343"]},{"id":"it","name":"Italy","flag":"🇮🇹","colors":["#009246","#ffffff","#ce2b37"]},{"id":"nl","name":"Netherlands","flag":"🇳🇱","colors":["#ae1c28","#ffffff","#21468b"]},{"id":"ar","name":"Argentina","flag":"🇦🇷","colors":["#75aadb","#ffffff","#f6b33f"]},{"id":"br","name":"Brazil","flag":"🇧🇷","colors":["#139b49","#ffd447","#1b55a5"]},{"id":"mx","name":"Mexico","flag":"🇲🇽","colors":["#0c8c57","#ffffff","#d43f3a"]},{"id":"co","name":"Colombia","flag":"🇨🇴","colors":["#fcd116","#003893","#ce1126"]},{"id":"us","name":"United States","flag":"🇺🇸","colors":["#ffffff","#b31942","#0a3161"]},{"id":"ca","name":"Canada","flag":"🇨🇦","colors":["#ff0000","#ffffff","#8a1538"]},{"id":"uy","name":"Uruguay","flag":"🇺🇾","colors":["#ffffff","#0038a8","#000000"]},{"id":"ec","name":"Ecuador","flag":"🇪🇨","colors":["#f9d33a","#1f5aa6","#d13d32"]},{"id":"cl","name":"Chile","flag":"🇨🇱","colors":["#ffffff","#d52b1e","#0039a6"]}]
    const groups = [
      { id: 'grp-A', name: 'Group A', teams: ['fr', 'de', 'it', 'cl'] },
      { id: 'grp-B', name: 'Group B', teams: ['es', 'eng', 'nl', 'ec'] },
      { id: 'grp-C', name: 'Group C', teams: ['pt', 'ar', 'mx', 'ca'] },
      { id: 'grp-D', name: 'Group D', teams: ['br', 'co', 'us', 'uy'] }
    ]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":[null,null],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"France vs Germany","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Spain vs England","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Portugal vs Italy","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"fr","score":"6/8","prize":"$540"},{"user":"amara","team":"es","score":"5/8","prize":"$360"},{"user":"vera","team":"de","score":"5/8","prize":"$270"},{"user":"diego","team":"pt","score":"4/8","prize":"$195"},{"user":"milo","team":"nl","score":"4/8","prize":"$140"},{"user":"kenji","team":"eng","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"fr","record":"4-1","trust":"99.2%"},{"user":"freya","team":"es","record":"4-1","trust":"98.9%"},{"user":"vera","team":"de","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"it","record":"3-2","trust":"98.1%"},{"user":"milo","team":"pt","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"fr","keeper":"vera","keeperTeam":"de","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"de","keeper":"captain","keeperTeam":"fr","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"fr","keeper":"milo","keeperTeam":"pt","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","France vs Germany is the next Round of 16 room. Picks are open until kickoff."],["Next","Spain vs England follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","France vs Germany e a proxima sala. Palpites abertos ate o inicio."],["Next","Spain vs England vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","France vs Germany es la proxima sala. Picks abiertos hasta el inicio."],["Next","Spain vs England sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","France vs Germany est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Spain vs England suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"France/Germany room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Spain/England pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, groups, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // Champions League Knockout
  const champions_league_knockout_data = (function () {
    const teams = [{"id":"rm","name":"Real Madrid","flag":"🇪🇸","colors":["#ffffff","#00529f","#f7c600"]},{"id":"mc","name":"Man City","flag":"🏴","colors":["#6cabdd","#ffffff","#1c2044"]},{"id":"bay","name":"Bayern","flag":"🇩🇪","colors":["#dc052d","#ffffff","#0066b2"]},{"id":"psg","name":"PSG","flag":"🇫🇷","colors":["#004170","#da291c","#ffffff"]},{"id":"liv","name":"Liverpool","flag":"🏴","colors":["#c8102e","#ffffff","#00b2a9"]},{"id":"fcb","name":"Barcelona","flag":"🇪🇸","colors":["#a50044","#004d98","#edff00"]},{"id":"juv","name":"Juventus","flag":"🇮🇹","colors":["#000000","#ffffff","#d6d6d6"]},{"id":"dor","name":"Dortmund","flag":"🇩🇪","colors":["#fde100","#000000","#f0f0f0"]},{"id":"atm","name":"Atletico","flag":"🇪🇸","colors":["#cb3524","#ffffff","#1a3c6e"]},{"id":"int","name":"Inter","flag":"🇮🇹","colors":["#010e80","#000000","#ffffff"]},{"id":"mil","name":"AC Milan","flag":"🇮🇹","colors":["#fb090b","#000000","#ffffff"]},{"id":"ars","name":"Arsenal","flag":"🏴","colors":["#ef0107","#ffffff","#023474"]},{"id":"che","name":"Chelsea","flag":"🏴","colors":["#034694","#ffffff","#d1d3d4"]},{"id":"mun","name":"Man United","flag":"🏴","colors":["#da291c","#ffffff","#000000"]},{"id":"ben","name":"Benfica","flag":"🇵🇹","colors":["#e30613","#ffffff","#000000"]},{"id":"por","name":"Porto","flag":"🇵🇹","colors":["#003399","#ffffff","#000000"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["rm","mc"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["bay","psg"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["liv","fcb"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["juv","dor"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["atm","int"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["mil","ars"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["che","mun"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["ben","por"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Real Madrid vs Man City","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Bayern vs PSG","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Liverpool vs Barcelona","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"rm","score":"6/8","prize":"$540"},{"user":"amara","team":"bay","score":"5/8","prize":"$360"},{"user":"vera","team":"mc","score":"5/8","prize":"$270"},{"user":"diego","team":"liv","score":"4/8","prize":"$195"},{"user":"milo","team":"juv","score":"4/8","prize":"$140"},{"user":"kenji","team":"psg","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"rm","record":"4-1","trust":"99.2%"},{"user":"freya","team":"bay","record":"4-1","trust":"98.9%"},{"user":"vera","team":"mc","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"fcb","record":"3-2","trust":"98.1%"},{"user":"milo","team":"liv","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"rm","keeper":"vera","keeperTeam":"mc","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"mc","keeper":"captain","keeperTeam":"rm","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"rm","keeper":"milo","keeperTeam":"liv","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Real Madrid vs Man City is the next Round of 16 room. Picks are open until kickoff."],["Next","Bayern vs PSG follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Real Madrid vs Man City e a proxima sala. Palpites abertos ate o inicio."],["Next","Bayern vs PSG vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Real Madrid vs Man City es la proxima sala. Picks abiertos hasta el inicio."],["Next","Bayern vs PSG sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Real Madrid vs Man City est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Bayern vs PSG suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Real Madrid/Man City room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Bayern/PSG pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // March Madness
  const march_madness_data = (function () {
    const teams = [{"id":"uconn","name":"UConn","flag":"🏀","colors":["#002868","#ffffff","#e4002b"]},{"id":"purdue","name":"Purdue","flag":"🏀","colors":["#ceb888","#000000","#ffffff"]},{"id":"unc","name":"North Carolina","flag":"🏀","colors":["#7bafd4","#ffffff","#101820"]},{"id":"duke","name":"Duke","flag":"🏀","colors":["#003087","#ffffff","#000000"]},{"id":"kansas","name":"Kansas","flag":"🏀","colors":["#0051ba","#ffffff","#e8000d"]},{"id":"zaga","name":"Gonzaga","flag":"🏀","colors":["#00295a","#ffffff","#c8102e"]},{"id":"houston","name":"Houston","flag":"🏀","colors":["#c8102e","#ffffff","#000000"]},{"id":"tn","name":"Tennessee","flag":"🏀","colors":["#ff8200","#ffffff","#000000"]},{"id":"auburn","name":"Auburn","flag":"🏀","colors":["#0c2340","#ffffff","#e87722"]},{"id":"ariz","name":"Arizona","flag":"🏀","colors":["#cc0033","#ffffff","#003366"]},{"id":"baylor","name":"Baylor","flag":"🏀","colors":["#154734","#ffffff","#ffb81c"]},{"id":"kent","name":"Kentucky","flag":"🏀","colors":["#0033a0","#ffffff","#000000"]},{"id":"marq","name":"Marquette","flag":"🏀","colors":["#003366","#ffffff","#f4c430"]},{"id":"mich","name":"Michigan St","flag":"🏀","colors":["#18453b","#ffffff","#000000"]},{"id":"fla","name":"Florida","flag":"🏀","colors":["#0021a5","#ffffff","#fa4616"]},{"id":"tex","name":"Texas","flag":"🏀","colors":["#bf5700","#ffffff","#333f48"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["uconn","purdue"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["unc","duke"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["kansas","zaga"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["houston","tn"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["auburn","ariz"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["baylor","kent"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["marq","mich"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["fla","tex"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"UConn vs Purdue","detail":"Round of 16 match room","live":true},{"status":"Today","title":"North Carolina vs Duke","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Kansas vs Gonzaga","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"uconn","score":"6/8","prize":"$540"},{"user":"amara","team":"unc","score":"5/8","prize":"$360"},{"user":"vera","team":"purdue","score":"5/8","prize":"$270"},{"user":"diego","team":"kansas","score":"4/8","prize":"$195"},{"user":"milo","team":"houston","score":"4/8","prize":"$140"},{"user":"kenji","team":"duke","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"uconn","record":"4-1","trust":"99.2%"},{"user":"freya","team":"unc","record":"4-1","trust":"98.9%"},{"user":"vera","team":"purdue","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"zaga","record":"3-2","trust":"98.1%"},{"user":"milo","team":"kansas","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"uconn","keeper":"vera","keeperTeam":"purdue","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"purdue","keeper":"captain","keeperTeam":"uconn","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"uconn","keeper":"milo","keeperTeam":"kansas","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","UConn vs Purdue is the next Round of 16 room. Picks are open until kickoff."],["Next","North Carolina vs Duke follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","UConn vs Purdue e a proxima sala. Palpites abertos ate o inicio."],["Next","North Carolina vs Duke vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","UConn vs Purdue es la proxima sala. Picks abiertos hasta el inicio."],["Next","North Carolina vs Duke sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","UConn vs Purdue est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","North Carolina vs Duke suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"UConn/Purdue room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"North Carolina/Duke pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // NBA / NHL / MLB Playoffs
  const pro_playoffs_data = (function () {
    const teams = [{"id":"lal","name":"Lakers","flag":"🏆","colors":["#552583","#fdb927","#000000"]},{"id":"bos","name":"Celtics","flag":"🏆","colors":["#007a33","#ffffff","#000000"]},{"id":"gs","name":"Warriors","flag":"🏆","colors":["#1d428a","#ffc72c","#ffffff"]},{"id":"den","name":"Nuggets","flag":"🏆","colors":["#0e2240","#fec524","#1d428a"]},{"id":"mia","name":"Heat","flag":"🏆","colors":["#98002e","#f9a01b","#000000"]},{"id":"phi","name":"76ers","flag":"🏆","colors":["#006bb6","#ed174c","#ffffff"]},{"id":"mil","name":"Bucks","flag":"🏆","colors":["#00471b","#eee1c6","#ffffff"]},{"id":"dal","name":"Mavericks","flag":"🏆","colors":["#00538c","#b8c4ca","#000000"]},{"id":"col","name":"Avalanche","flag":"🏆","colors":["#6f263d","#236192","#a2aaad"]},{"id":"edm","name":"Oilers","flag":"🏆","colors":["#041e42","#ff4c00","#ffffff"]},{"id":"nyr","name":"Rangers","flag":"🏆","colors":["#0033a0","#c8102e","#ffffff"]},{"id":"tb","name":"Lightning","flag":"🏆","colors":["#002868","#ffffff","#000000"]},{"id":"nyy","name":"Yankees","flag":"🏆","colors":["#003087","#ffffff","#e4002c"]},{"id":"lad","name":"Dodgers","flag":"🏆","colors":["#005a9c","#ffffff","#ef3e42"]},{"id":"houa","name":"Astros","flag":"🏆","colors":["#002d62","#eb6e1f","#ffffff"]},{"id":"atl","name":"Braves","flag":"🏆","colors":["#ce1141","#13274f","#ffffff"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["lal","bos"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["gs","den"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["mia","phi"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["mil","dal"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["col","edm"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["nyr","tb"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["nyy","lad"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["houa","atl"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Lakers vs Celtics","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Warriors vs Nuggets","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Heat vs 76ers","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"lal","score":"6/8","prize":"$540"},{"user":"amara","team":"gs","score":"5/8","prize":"$360"},{"user":"vera","team":"bos","score":"5/8","prize":"$270"},{"user":"diego","team":"mia","score":"4/8","prize":"$195"},{"user":"milo","team":"mil","score":"4/8","prize":"$140"},{"user":"kenji","team":"den","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"lal","record":"4-1","trust":"99.2%"},{"user":"freya","team":"gs","record":"4-1","trust":"98.9%"},{"user":"vera","team":"bos","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"phi","record":"3-2","trust":"98.1%"},{"user":"milo","team":"mia","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"lal","keeper":"vera","keeperTeam":"bos","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"bos","keeper":"captain","keeperTeam":"lal","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"lal","keeper":"milo","keeperTeam":"mia","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Lakers vs Celtics is the next Round of 16 room. Picks are open until kickoff."],["Next","Warriors vs Nuggets follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Lakers vs Celtics e a proxima sala. Palpites abertos ate o inicio."],["Next","Warriors vs Nuggets vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Lakers vs Celtics es la proxima sala. Picks abiertos hasta el inicio."],["Next","Warriors vs Nuggets sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Lakers vs Celtics est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Warriors vs Nuggets suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Lakers/Celtics room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Warriors/Nuggets pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // Tennis Grand Slams
  const tennis_grand_slams_data = (function () {
    const teams = [{"id":"alcaraz","name":"Alcaraz","flag":"🎾","colors":["#ffffff","#22c55e","#15803d"]},{"id":"djok","name":"Djokovic","flag":"🎾","colors":["#1e3a8a","#ffffff","#1d4ed8"]},{"id":"sinner","name":"Sinner","flag":"🎾","colors":["#166534","#ffffff","#000000"]},{"id":"nadal","name":"Nadal","flag":"🎾","colors":["#dc2626","#facc15","#000000"]},{"id":"medv","name":"Medvedev","flag":"🎾","colors":["#ffffff","#3b82f6","#1e40af"]},{"id":"zverev","name":"Zverev","flag":"🎾","colors":["#facc15","#000000","#ffffff"]},{"id":"rune","name":"Rune","flag":"🎾","colors":["#ef4444","#ffffff","#000000"]},{"id":"tsits","name":"Tsitsipas","flag":"🎾","colors":["#0ea5e9","#ffffff","#000000"]},{"id":"swia","name":"Swiatek","flag":"🎾","colors":["#ec4899","#ffffff","#000000"]},{"id":"saba","name":"Sabalenka","flag":"🎾","colors":["#a855f7","#ffffff","#000000"]},{"id":"ryba","name":"Rybakina","flag":"🎾","colors":["#14b8a6","#ffffff","#000000"]},{"id":"gauff","name":"Gauff","flag":"🎾","colors":["#22c55e","#ffffff","#000000"]},{"id":"jabeu","name":"Jabeur","flag":"🎾","colors":["#f97316","#ffffff","#000000"]},{"id":"peg","name":"Pegula","flag":"🎾","colors":["#3b82f6","#ffffff","#000000"]},{"id":"vond","name":"Vondrousova","flag":"🎾","colors":["#eab308","#ffffff","#000000"]},{"id":"krejc","name":"Krejcikova","flag":"🎾","colors":["#ef4444","#ffffff","#000000"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["alcaraz","djok"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["sinner","nadal"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["medv","zverev"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["rune","tsits"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["swia","saba"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["ryba","gauff"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["jabeu","peg"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["vond","krejc"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Alcaraz vs Djokovic","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Sinner vs Nadal","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Medvedev vs Zverev","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"alcaraz","score":"6/8","prize":"$540"},{"user":"amara","team":"sinner","score":"5/8","prize":"$360"},{"user":"vera","team":"djok","score":"5/8","prize":"$270"},{"user":"diego","team":"medv","score":"4/8","prize":"$195"},{"user":"milo","team":"rune","score":"4/8","prize":"$140"},{"user":"kenji","team":"nadal","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"alcaraz","record":"4-1","trust":"99.2%"},{"user":"freya","team":"sinner","record":"4-1","trust":"98.9%"},{"user":"vera","team":"djok","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"zverev","record":"3-2","trust":"98.1%"},{"user":"milo","team":"medv","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"alcaraz","keeper":"vera","keeperTeam":"djok","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"djok","keeper":"captain","keeperTeam":"alcaraz","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"alcaraz","keeper":"milo","keeperTeam":"medv","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Alcaraz vs Djokovic is the next Round of 16 room. Picks are open until kickoff."],["Next","Sinner vs Nadal follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Alcaraz vs Djokovic e a proxima sala. Palpites abertos ate o inicio."],["Next","Sinner vs Nadal vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Alcaraz vs Djokovic es la proxima sala. Picks abiertos hasta el inicio."],["Next","Sinner vs Nadal sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Alcaraz vs Djokovic est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Sinner vs Nadal suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Alcaraz/Djokovic room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Sinner/Nadal pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // Esports Major
  const esports_major_data = (function () {
    const teams = [{"id":"t1","name":"T1","flag":"🎮","colors":["#e2012d","#000000","#ffffff"]},{"id":"g2","name":"G2","flag":"🎮","colors":["#000000","#ffffff","#c8102e"]},{"id":"fnc","name":"Fnatic","flag":"🎮","colors":["#ff5900","#000000","#ffffff"]},{"id":"tl","name":"Team Liquid","flag":"🎮","colors":["#0c2340","#ffffff","#00aeef"]},{"id":"navi","name":"NAVI","flag":"🎮","colors":["#ffee00","#000000","#ffffff"]},{"id":"vit","name":"Vitality","flag":"🎮","colors":["#f9e300","#000000","#ffffff"]},{"id":"c9","name":"Cloud9","flag":"🎮","colors":["#00aeef","#ffffff","#000000"]},{"id":"sen","name":"Sentinels","flag":"🎮","colors":["#ce0e2d","#000000","#ffffff"]},{"id":"gen","name":"Gen.G","flag":"🎮","colors":["#aa8a30","#000000","#ffffff"]},{"id":"blg","name":"Bilibili","flag":"🎮","colors":["#00a1d6","#ffffff","#000000"]},{"id":"faze","name":"FaZe","flag":"🎮","colors":["#ff0000","#000000","#ffffff"]},{"id":"og","name":"OG","flag":"🎮","colors":["#002b45","#ffffff","#000000"]},{"id":"eg","name":"Evil Geniuses","flag":"🎮","colors":["#0c1220","#ffffff","#d3af37"]},{"id":"100t","name":"100 Thieves","flag":"🎮","colors":["#d31f3c","#000000","#ffffff"]},{"id":"tsm","name":"TSM","flag":"🎮","colors":["#000000","#ffffff","#c8102e"]},{"id":"koi","name":"KOI","flag":"🎮","colors":["#0d1b2a","#ffffff","#ff4d6d"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["t1","g2"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["fnc","tl"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["navi","vit"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["c9","sen"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["gen","blg"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["faze","og"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["eg","100t"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["tsm","koi"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"T1 vs G2","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Fnatic vs Team Liquid","detail":"Round of 16 match room","live":false},{"status":"Today","title":"NAVI vs Vitality","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"t1","score":"6/8","prize":"$540"},{"user":"amara","team":"fnc","score":"5/8","prize":"$360"},{"user":"vera","team":"g2","score":"5/8","prize":"$270"},{"user":"diego","team":"navi","score":"4/8","prize":"$195"},{"user":"milo","team":"c9","score":"4/8","prize":"$140"},{"user":"kenji","team":"tl","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"t1","record":"4-1","trust":"99.2%"},{"user":"freya","team":"fnc","record":"4-1","trust":"98.9%"},{"user":"vera","team":"g2","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"vit","record":"3-2","trust":"98.1%"},{"user":"milo","team":"navi","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"t1","keeper":"vera","keeperTeam":"g2","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"g2","keeper":"captain","keeperTeam":"t1","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"t1","keeper":"milo","keeperTeam":"navi","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","T1 vs G2 is the next Round of 16 room. Picks are open until kickoff."],["Next","Fnatic vs Team Liquid follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","T1 vs G2 e a proxima sala. Palpites abertos ate o inicio."],["Next","Fnatic vs Team Liquid vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","T1 vs G2 es la proxima sala. Picks abiertos hasta el inicio."],["Next","Fnatic vs Team Liquid sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","T1 vs G2 est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Fnatic vs Team Liquid suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"T1/G2 room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Fnatic/Team Liquid pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // SailGP Companion
  const sailgp_companion_data = (function () {
    const teams = [{"id":"aus","name":"Australia","flag":"🇦🇺","colors":["#012169","#ffcd00","#00843d"]},{"id":"gbr","name":"Great Britain","flag":"🇬🇧","colors":["#ffffff","#d41f35","#1c3764"]},{"id":"nz","name":"New Zealand","flag":"🇳🇿","colors":["#00247d","#ffffff","#cc142b"]},{"id":"usa","name":"United States","flag":"🇺🇸","colors":["#ffffff","#b31942","#0a3161"]},{"id":"fra","name":"France","flag":"🇫🇷","colors":["#1d3d8f","#ffffff","#d84a3a"]},{"id":"den","name":"Denmark","flag":"🇩🇰","colors":["#c8102e","#ffffff","#000000"]},{"id":"jpn","name":"Japan","flag":"🇯🇵","colors":["#f6f6f6","#d91f3c","#0a2f68"]},{"id":"esp","name":"Spain","flag":"🇪🇸","colors":["#c60b1e","#ffc400","#75131a"]},{"id":"ger","name":"Germany","flag":"🇩🇪","colors":["#000000","#dd0000","#ffce00"]},{"id":"can","name":"Canada","flag":"🇨🇦","colors":["#ff0000","#ffffff","#8a1538"]},{"id":"sui","name":"Switzerland","flag":"🇨🇭","colors":["#d71920","#ffffff","#901019"]},{"id":"bra","name":"Brazil","flag":"🇧🇷","colors":["#139b49","#ffd447","#1b55a5"]},{"id":"ita","name":"Italy","flag":"🇮🇹","colors":["#009246","#ffffff","#ce2b37"]},{"id":"ned","name":"Netherlands","flag":"🇳🇱","colors":["#ae1c28","#ffffff","#21468b"]},{"id":"arg","name":"Argentina","flag":"🇦🇷","colors":["#75aadb","#ffffff","#f6b33f"]},{"id":"swe","name":"Sweden","flag":"🇸🇪","colors":["#006aa7","#fecc00","#0b4f7a"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["aus","gbr"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["nz","usa"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["fra","den"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["jpn","esp"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["ger","can"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["sui","bra"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["ita","ned"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["arg","swe"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Australia vs Great Britain","detail":"Round of 16 match room","live":true},{"status":"Today","title":"New Zealand vs United States","detail":"Round of 16 match room","live":false},{"status":"Today","title":"France vs Denmark","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"aus","score":"6/8","prize":"$540"},{"user":"amara","team":"nz","score":"5/8","prize":"$360"},{"user":"vera","team":"gbr","score":"5/8","prize":"$270"},{"user":"diego","team":"fra","score":"4/8","prize":"$195"},{"user":"milo","team":"jpn","score":"4/8","prize":"$140"},{"user":"kenji","team":"usa","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"aus","record":"4-1","trust":"99.2%"},{"user":"freya","team":"nz","record":"4-1","trust":"98.9%"},{"user":"vera","team":"gbr","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"den","record":"3-2","trust":"98.1%"},{"user":"milo","team":"fra","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"aus","keeper":"vera","keeperTeam":"gbr","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"gbr","keeper":"captain","keeperTeam":"aus","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"aus","keeper":"milo","keeperTeam":"fra","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Australia vs Great Britain is the next Round of 16 room. Picks are open until kickoff."],["Next","New Zealand vs United States follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Australia vs Great Britain e a proxima sala. Palpites abertos ate o inicio."],["Next","New Zealand vs United States vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Australia vs Great Britain es la proxima sala. Picks abiertos hasta el inicio."],["Next","New Zealand vs United States sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Australia vs Great Britain est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","New Zealand vs United States suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Australia/Great Britain room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"New Zealand/United States pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // Reality / Creator Tournaments
  const creator_reality_brackets_data = (function () {
    const teams = [{"id":"alpha","name":"Alpha Squad","flag":"⭐","colors":["#d946ef","#22c55e","#ffffff"]},{"id":"beta","name":"Beta House","flag":"⭐","colors":["#22c55e","#d946ef","#ffffff"]},{"id":"gamma","name":"Gamma Crew","flag":"⭐","colors":["#f59e0b","#ec4899","#ffffff"]},{"id":"delta","name":"Delta Fam","flag":"⭐","colors":["#3b82f6","#8b5cf6","#ffffff"]},{"id":"echo","name":"Echo Hive","flag":"⭐","colors":["#ef4444","#f97316","#ffffff"]},{"id":"foxy","name":"Foxy Clan","flag":"⭐","colors":["#ec4899","#f59e0b","#ffffff"]},{"id":"ghost","name":"Ghost Pack","flag":"⭐","colors":["#64748b","#94a3b8","#ffffff"]},{"id":"hype","name":"Hype House","flag":"⭐","colors":["#8b5cf6","#06b6d4","#ffffff"]},{"id":"ivy","name":"Ivy League","flag":"⭐","colors":["#10b981","#3b82f6","#ffffff"]},{"id":"jolt","name":"Jolt Squad","flag":"⭐","colors":["#f43f5e","#3b82f6","#ffffff"]},{"id":"krew","name":"Krew","flag":"⭐","colors":["#eab308","#ef4444","#ffffff"]},{"id":"luxe","name":"Luxe Life","flag":"⭐","colors":["#ec4899","#6366f1","#ffffff"]},{"id":"muse","name":"Muse Circle","flag":"⭐","colors":["#06b6d4","#d946ef","#ffffff"]},{"id":"nova","name":"Nova Crew","flag":"⭐","colors":["#f97316","#eab308","#ffffff"]},{"id":"orbit","name":"Orbit House","flag":"⭐","colors":["#6366f1","#22c55e","#ffffff"]},{"id":"pulse","name":"Pulse Fam","flag":"⭐","colors":["#14b8a6","#f43f5e","#ffffff"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["alpha","beta"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["gamma","delta"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["echo","foxy"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["ghost","hype"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["ivy","jolt"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["krew","luxe"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["muse","nova"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["orbit","pulse"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Alpha Squad vs Beta House","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Gamma Crew vs Delta Fam","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Echo Hive vs Foxy Clan","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"alpha","score":"6/8","prize":"$540"},{"user":"amara","team":"gamma","score":"5/8","prize":"$360"},{"user":"vera","team":"beta","score":"5/8","prize":"$270"},{"user":"diego","team":"echo","score":"4/8","prize":"$195"},{"user":"milo","team":"ghost","score":"4/8","prize":"$140"},{"user":"kenji","team":"delta","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"alpha","record":"4-1","trust":"99.2%"},{"user":"freya","team":"gamma","record":"4-1","trust":"98.9%"},{"user":"vera","team":"beta","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"foxy","record":"3-2","trust":"98.1%"},{"user":"milo","team":"echo","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"alpha","keeper":"vera","keeperTeam":"beta","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"beta","keeper":"captain","keeperTeam":"alpha","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"alpha","keeper":"milo","keeperTeam":"echo","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Alpha Squad vs Beta House is the next Round of 16 room. Picks are open until kickoff."],["Next","Gamma Crew vs Delta Fam follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Alpha Squad vs Beta House e a proxima sala. Palpites abertos ate o inicio."],["Next","Gamma Crew vs Delta Fam vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Alpha Squad vs Beta House es la proxima sala. Picks abiertos hasta el inicio."],["Next","Gamma Crew vs Delta Fam sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Alpha Squad vs Beta House est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Gamma Crew vs Delta Fam suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Alpha Squad/Beta House room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Gamma Crew/Delta Fam pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // Oscars / Grammys / Eurovision
  const awards_prediction_pools_data = (function () {
    const teams = [{"id":"oppen","name":"Oppenheimer","flag":"🎬","colors":["#000000","#f59e0b","#ffffff"]},{"id":"barb","name":"Barbie","flag":"🎬","colors":["#ec4899","#f472b6","#ffffff"]},{"id":"poor","name":"Poor Things","flag":"🎬","colors":["#10b981","#f59e0b","#ffffff"]},{"id":"kill","name":"Killers of the Flower Moon","flag":"🎬","colors":["#78350f","#d97706","#ffffff"]},{"id":"hold","name":"Holdovers","flag":"🎬","colors":["#3b82f6","#facc15","#ffffff"]},{"id":"past","name":"Past Lives","flag":"🎬","colors":["#f43f5e","#fb7185","#ffffff"]},{"id":"anat","name":"Anatomy of a Fall","flag":"🎬","colors":["#1e293b","#94a3b8","#ffffff"]},{"id":"zone","name":"Zone of Interest","flag":"🎬","colors":["#000000","#ef4444","#ffffff"]},{"id":"tayl","name":"Taylor Swift","flag":"🎵","colors":["#a855f7","#e879f9","#ffffff"]},{"id":"sza","name":"SZA","flag":"🎵","colors":["#22c55e","#ffffff","#000000"]},{"id":"bilal","name":"Bilal Hassani","flag":"🎵","colors":["#06b6d4","#f472b6","#ffffff"]},{"id":"lore","name":"Loreen","flag":"🎵","colors":["#f59e0b","#000000","#ffffff"]},{"id":"kaar","name":"Käärijä","flag":"🎵","colors":["#16a34a","#000000","#ffffff"]},{"id":"mahn","name":"Mahmood","flag":"🎵","colors":["#ef4444","#10b981","#ffffff"]},{"id":"corn","name":"Cornelia Jakobs","flag":"🎵","colors":["#3b82f6","#facc15","#ffffff"]},{"id":"samr","name":"Sam Ryder","flag":"🎵","colors":["#eab308","#ec4899","#ffffff"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["oppen","barb"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["poor","kill"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["hold","past"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["anat","zone"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["tayl","sza"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["bilal","lore"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["kaar","mahn"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["corn","samr"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Oppenheimer vs Barbie","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Poor Things vs Killers of the Flower Moon","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Holdovers vs Past Lives","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"oppen","score":"6/8","prize":"$540"},{"user":"amara","team":"poor","score":"5/8","prize":"$360"},{"user":"vera","team":"barb","score":"5/8","prize":"$270"},{"user":"diego","team":"hold","score":"4/8","prize":"$195"},{"user":"milo","team":"anat","score":"4/8","prize":"$140"},{"user":"kenji","team":"kill","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"oppen","record":"4-1","trust":"99.2%"},{"user":"freya","team":"poor","record":"4-1","trust":"98.9%"},{"user":"vera","team":"barb","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"past","record":"3-2","trust":"98.1%"},{"user":"milo","team":"hold","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"oppen","keeper":"vera","keeperTeam":"barb","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"barb","keeper":"captain","keeperTeam":"oppen","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"oppen","keeper":"milo","keeperTeam":"hold","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Oppenheimer vs Barbie is the next Round of 16 room. Picks are open until kickoff."],["Next","Poor Things vs Killers of the Flower Moon follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Oppenheimer vs Barbie e a proxima sala. Palpites abertos ate o inicio."],["Next","Poor Things vs Killers of the Flower Moon vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Oppenheimer vs Barbie es la proxima sala. Picks abiertos hasta el inicio."],["Next","Poor Things vs Killers of the Flower Moon sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Oppenheimer vs Barbie est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Poor Things vs Killers of the Flower Moon suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Oppenheimer/Barbie room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Poor Things/Killers of the Flower Moon pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  // School / Office / Pub / Rec Sports
  const local_leagues_data = (function () {
    const teams = [{"id":"phoenix","name":"Phoenix FC","flag":"⚽","colors":["#ef4444","#f97316","#ffffff"]},{"id":"titan","name":"Titan United","flag":"⚽","colors":["#3b82f6","#1d4ed8","#ffffff"]},{"id":"rover","name":"Rovers","flag":"⚽","colors":["#22c55e","#15803d","#ffffff"]},{"id":"sting","name":"Stingers","flag":"⚽","colors":["#eab308","#ca8a04","#ffffff"]},{"id":"thund","name":"Thunder","flag":"⚽","colors":["#a855f7","#7e22ce","#ffffff"]},{"id":"shark","name":"Sharks","flag":"⚽","colors":["#06b6d4","#0891b2","#ffffff"]},{"id":"vultu","name":"Vultures","flag":"⚽","colors":["#f43f5e","#be123c","#ffffff"]},{"id":"panda","name":"Pandas","flag":"⚽","colors":["#10b981","#047857","#ffffff"]},{"id":"eagle","name":"Eagles","flag":"🏈","colors":["#1e3a8a","#facc15","#ffffff"]},{"id":"lion","name":"Lions","flag":"🏈","colors":["#c2410c","#fdba74","#ffffff"]},{"id":"hawk","name":"Hawks","flag":"🏀","colors":["#7c3aed","#c4b5fd","#ffffff"]},{"id":"blaze","name":"Blazers","flag":"🏀","colors":["#dc2626","#fca5a5","#ffffff"]},{"id":"orca","name":"Orcas","flag":"🏐","colors":["#0e7490","#67e8f9","#ffffff"]},{"id":"cobra","name":"Cobras","flag":"🏐","colors":["#15803d","#86efac","#ffffff"]},{"id":"falcon","name":"Falcons","flag":"🥎","colors":["#b45309","#fcd34d","#ffffff"]},{"id":"wolf","name":"Wolves","flag":"🥎","colors":["#4b5563","#9ca3af","#ffffff"]}]
    const round32Matches = [{"id":"r32-1","time":"Round of 16","status":"Open","slots":["phoenix","titan"],"score":[null,null]},{"id":"r32-2","time":"Round of 16","status":"Open","slots":["rover","sting"],"score":[null,null]},{"id":"r32-3","time":"Round of 16","status":"Open","slots":["thund","shark"],"score":[null,null]},{"id":"r32-4","time":"Round of 16","status":"Open","slots":["vultu","panda"],"score":[null,null]},{"id":"r32-5","time":"Round of 16","status":"Open","slots":["eagle","lion"],"score":[null,null]},{"id":"r32-6","time":"Round of 16","status":"Open","slots":["hawk","blaze"],"score":[null,null]},{"id":"r32-7","time":"Round of 16","status":"Open","slots":["orca","cobra"],"score":[null,null]},{"id":"r32-8","time":"Round of 16","status":"Open","slots":["falcon","wolf"],"score":[null,null]}]
    const bracketLinks = [{"from":["r32-1","r32-2"],"to":"r16-1"},{"from":["r32-3","r32-4"],"to":"r16-2"},{"from":["r32-5","r32-6"],"to":"r16-3"},{"from":["r32-7","r32-8"],"to":"r16-4"},{"from":["r16-1","r16-2"],"to":"qf-1"},{"from":["r16-3","r16-4"],"to":"qf-2"},{"from":["qf-1","qf-2"],"to":"sf-1"},{"from":["sf-1"],"to":"final-1"}]
    const bracketMatchIds = ["r32-1","r32-2","r32-3","r32-4","r32-5","r32-6","r32-7","r32-8","r16-1","r16-2","r16-3","r16-4","qf-1","qf-2","sf-1","final-1"]
    const homeFixtures = [{"status":"Today","title":"Phoenix FC vs Titan United","detail":"Round of 16 match room","live":true},{"status":"Today","title":"Rovers vs Stingers","detail":"Round of 16 match room","live":false},{"status":"Today","title":"Thunder vs Sharks","detail":"Round of 16 match room","live":false}]
    const leaders = [{"user":"lina","team":"phoenix","score":"6/8","prize":"$540"},{"user":"amara","team":"rover","score":"5/8","prize":"$360"},{"user":"vera","team":"titan","score":"5/8","prize":"$270"},{"user":"diego","team":"thund","score":"4/8","prize":"$195"},{"user":"milo","team":"vultu","score":"4/8","prize":"$140"},{"user":"kenji","team":"sting","score":"3/8","prize":"$95"}]
    const gameLeaderboardRows = [{"user":"captain","team":"phoenix","record":"4-1","trust":"99.2%"},{"user":"freya","team":"rover","record":"4-1","trust":"98.9%"},{"user":"vera","team":"titan","record":"3-2","trust":"98.7%"},{"user":"kwame","team":"shark","record":"3-2","trust":"98.1%"},{"user":"milo","team":"thund","record":"3-2","trust":"97.9%"}]
    const gameRounds = [{"shooter":"captain","shooterTeam":"phoenix","keeper":"vera","keeperTeam":"titan","aim":"right-high","dive":"right-high","power":3,"curve":1,"releaseTick":42,"keeperTick":43},{"shooter":"vera","shooterTeam":"titan","keeper":"captain","keeperTeam":"phoenix","aim":"left-low","dive":"center-low","power":4,"curve":-1,"releaseTick":39,"keeperTick":41},{"shooter":"captain","shooterTeam":"phoenix","keeper":"milo","keeperTeam":"thund","aim":"center-high","dive":"left-high","power":4,"curve":2,"releaseTick":45,"keeperTick":44}]
    const commentary = {"EN":[["Today","Phoenix FC vs Titan United is the next Round of 16 room. Picks are open until kickoff."],["Next","Rovers vs Stingers follows later today."],["Bracket","Pool impact is live, but the fallback feed will not invent results before they happen."]],"PT":[["Today","Phoenix FC vs Titan United e a proxima sala. Palpites abertos ate o inicio."],["Next","Rovers vs Stingers vem depois."],["Bracket","O impacto do bolao esta ativo, mas o fallback nao inventa resultados."]],"ES":[["Today","Phoenix FC vs Titan United es la proxima sala. Picks abiertos hasta el inicio."],["Next","Rovers vs Stingers sigue mas tarde."],["Bracket","El impacto del pool esta activo, pero el fallback no inventa resultados."]],"FR":[["Today","Phoenix FC vs Titan United est la prochaine salle. Picks ouverts jusqu au coup d envoi."],["Next","Rovers vs Stingers suit ensuite."],["Bracket","L impact du pool est actif, mais le fallback ne fabrique pas de resultats."]]}
    const defaultChat = [{"user":"lina","text":"Phoenix FC/Titan United room is up. No fake result until the feed lands.","time":"Today"},{"user":"vera","text":"Rovers/Stingers pool is next on my list.","time":"Next"},{"user":"ash","text":"Bracket is still Round of 16.","time":"R16"}]
    return { teams, round32Matches, bracketLinks, bracketMatchIds, homeFixtures, leaders, gameLeaderboardRows, gameRounds, commentary, defaultChat }
  })()

  const fits = [
    {
      id: 'euros-copa-america',
      title: 'Euros / Copa America',
      category: 'soccer',
      entrantShape: 'team',
      templateKind: 'group-plus-knockout',
      defaultTeam: 'fr',
      theme: makeTheme('#3b82f6', '#ef4444', '#1d4ed8', '#1e293b', '#eff6ff', '#ffffff'),
      data: euros_copa_america_data
    },
    {
      id: 'champions-league-knockout',
      title: 'Champions League Knockout',
      category: 'soccer',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 'rm',
      theme: makeTheme('#0ea5e9', '#f59e0b', '#0369a1', '#0f172a', '#f0f9ff', '#ffffff'),
      data: champions_league_knockout_data
    },
    {
      id: 'march-madness',
      title: 'March Madness',
      category: 'basketball',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 'uconn',
      theme: makeTheme('#f97316', '#3b82f6', '#c2410c', '#2a1510', '#fff7ed', '#ffffff'),
      data: march_madness_data
    },
    {
      id: 'pro-playoffs',
      title: 'NBA / NHL / MLB Playoffs',
      category: 'pro-sports',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 'lal',
      theme: makeTheme('#8b5cf6', '#f43f5e', '#6d28d9', '#1a1025', '#f5f3ff', '#ffffff'),
      data: pro_playoffs_data
    },
    {
      id: 'tennis-grand-slams',
      title: 'Tennis Grand Slams',
      category: 'tennis',
      entrantShape: 'player',
      templateKind: 'single-elimination',
      defaultTeam: 'alcaraz',
      theme: makeTheme('#10b981', '#f59e0b', '#047857', '#0f2c22', '#ecfdf5', '#ffffff'),
      data: tennis_grand_slams_data
    },
    {
      id: 'esports-major',
      title: 'Esports Major',
      category: 'esports',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 't1',
      theme: makeTheme('#ec4899', '#6366f1', '#be185d', '#1e1b4b', '#fdf2f8', '#ffffff'),
      data: esports_major_data
    },
    {
      id: 'sailgp-companion',
      title: 'SailGP Companion',
      category: 'sailing',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 'aus',
      theme: makeTheme('#06b6d4', '#f43f5e', '#0e7490', '#082f49', '#ecfeff', '#ffffff'),
      data: sailgp_companion_data
    },
    {
      id: 'creator-reality-brackets',
      title: 'Reality / Creator Tournaments',
      category: 'creator',
      entrantShape: 'creator',
      templateKind: 'single-elimination',
      defaultTeam: 'alpha',
      theme: makeTheme('#d946ef', '#22c55e', '#a21caf', '#2a0a2e', '#fdf4ff', '#ffffff'),
      data: creator_reality_brackets_data
    },
    {
      id: 'awards-prediction-pools',
      title: 'Oscars / Grammys / Eurovision',
      category: 'awards',
      entrantShape: 'nominee',
      templateKind: 'awards-card',
      defaultTeam: 'oppen',
      theme: makeTheme('#f59e0b', '#ec4899', '#b45309', '#2a1a08', '#fffbeb', '#ffffff'),
      data: awards_prediction_pools_data
    },
    {
      id: 'local-leagues',
      title: 'School / Office / Pub / Rec Sports',
      category: 'local',
      entrantShape: 'team',
      templateKind: 'single-elimination',
      defaultTeam: 'phoenix',
      theme: makeTheme('#22c55e', '#3b82f6', '#15803d', '#0f291e', '#f0fdf4', '#ffffff'),
      data: local_leagues_data
    },
  ]

  fits.forEach(fit => {
    root.registerFit(fit.id, {
      fitId: fit.id,
      title: fit.title,
      subtitle: 'Ultimate Sports',
      category: fit.category,
      entrantShape: fit.entrantShape,
      templateKind: fit.templateKind,
      defaultTeam: fit.defaultTeam,
      theme: fit.theme,
      teams: fit.data.teams,
      groups: fit.data.groups,
      pools: [{ tier: 10, entrants: 92, closes: '12h', max: 256, prize: '$920', heat: 'Open', rail: 'USDT demo' }, { tier: 25, entrants: 58, closes: '9h', max: 160, prize: '$1,450', heat: 'Hot', rail: 'USDT demo' }, { tier: 50, entrants: 32, closes: '7h', max: 96, prize: '$1,600', heat: 'Sharp', rail: 'USDT demo' }, { tier: 100, entrants: 16, closes: '5h', max: 64, prize: '$1,600', heat: 'Elite', rail: 'USDT demo' }],
      round32Matches: fit.data.round32Matches,
      bracketLinks: fit.data.bracketLinks,
      bracketMatchIds: fit.data.bracketMatchIds,
      homeFixtures: fit.data.homeFixtures,
      matchStats: fit.stats,
      leaders: fit.data.leaders,
      commentary: fit.data.commentary,
      defaultChat: fit.data.defaultChat,
      gameRounds: fit.data.gameRounds,
      gameLeaderboardRows: fit.data.gameLeaderboardRows,
      assets: root.defaultFitAssets(fit.id),
    })
  })
})(window)

