#!/usr/bin/env node
'use strict'

// Build a browser-loadable bundle of the pure Node engines in src/.
// The bundle exposes window.UltimateEngines with the same APIs the Node tests use.
//
// Usage:
//   node scripts/build-engines.mjs           # writes shell/engines.bundle.js
//   node scripts/build-engines.mjs --check   # verifies the bundle syntax only

import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)

const ROOT = join(__dirname, '..')
const OUT_FILE = join(ROOT, 'shell', 'engines.bundle.js')

// Dependency order: each module only requires earlier modules.
const MODULES = [
  { name: 'constants', file: 'src/constants.js' },
  { name: 'util', file: 'src/util.js' },
  { name: 'eventLog', file: 'src/event-log.js' },
  { name: 'scoring', file: 'src/scoring-engine.js' },
  { name: 'prediction', file: 'src/prediction-engine.js' },
  { name: 'pool', file: 'src/pool-engine.js' },
  { name: 'competition', file: 'src/competition-engine.js' }
]

const CHECK = process.argv.includes('--check')

function resolveRelative (baseId, relId) {
  if (!relId.startsWith('.')) return relId
  const baseDir = dirname(baseId)
  const joined = join(baseDir, relId)
  // Source files omit the .js extension in relative requires.
  return joined.endsWith('.js') ? joined : joined + '.js'
}

function rewriteRequires (baseId, source) {
  return source.replace(/require\(\s*['"]([^'"]+)['"]\s*\)/g, (match, relId) => {
    return `require('${resolveRelative(baseId, relId)}')`
  })
}

function wrapModule (id, source) {
  // Preserve the original source but rewrite relative requires to absolute module ids
  // so the browser require shim can resolve them.
  return `
modules['${id}'] = function (require, module, exports) {
${rewriteRequires(id, source).split('\n').map(line => '  ' + line).join('\n')}
}
`
}

async function build () {
  const sources = []
  for (const mod of MODULES) {
    const path = join(ROOT, mod.file)
    const source = await readFile(path, 'utf8')
    sources.push({ id: mod.file, source })
  }

  const bundleParts = [
    '/* Ultimate Sports engine bundle — generated by scripts/build-engines.mjs */',
    '/* Do not edit directly; rerun the build script. */',
    '(function (root) {',
    "  'use strict'",
    '  var modules = {}',
    '  var cache = {}',
    '',
    '  function require (id) {',
    '    if (cache[id]) return cache[id].exports',
    '    var factory = modules[id]',
    "    if (!factory) throw new Error('Module not found: ' + id)",
    '    var module = { exports: {} }',
    '    cache[id] = module',
    '    factory(require, module, module.exports)',
    '    return module.exports',
    '  }',
    ''
  ]

  for (const { id, source } of sources) {
    bundleParts.push(wrapModule(id, source))
  }

  const exports = MODULES.map(mod => `    ${mod.name}: require('${mod.file}')`).join(',\n')
  bundleParts.push(`
  root.UltimateEngines = {
${exports}
  }
})(typeof window !== 'undefined' ? window : globalThis)
`)

  return bundleParts.join('\n')
}

async function main () {
  const bundle = await build()

  if (CHECK) {
    // Syntax check by evaluating in a minimal VM-like context.
    const vm = await import('node:vm')
    const context = { window: {}, console, Math, JSON, Date, Set, Map, Array, Object, String, Number, Boolean, RegExp, Error, Uint8Array, Buffer: {} }
    vm.createContext(context)
    vm.runInContext(bundle, context, { filename: OUT_FILE })
    if (!context.window.UltimateEngines) throw new Error('bundle did not expose UltimateEngines')
    console.log('Engine bundle syntax OK; exposed keys:', Object.keys(context.window.UltimateEngines).join(', '))
    return
  }

  await writeFile(OUT_FILE, bundle)
  console.log('Wrote', OUT_FILE)
}

main().catch((err) => {
  console.error('[build-engines] error:', err)
  process.exit(1)
})
